package com.example.minicpm_v_demo

import java.io.File
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStream

data class CachedImageSource(
    val file: File,
    val byteCount: Long,
    val token: String = file.name
)

class ImageSourceUnreadableException(cause: Throwable? = null) : IOException(cause)

class ImageSourceTooLargeException : IOException()

/**
 * Copies a selected content URI into an app-private cache with one source open.
 * Some vendor document providers issue transient streams that cannot be reopened.
 */
class ImageSourceCache(
    cacheDirectory: File,
    private val maxBytes: Long
) {
    private val directory = cacheDirectory.canonicalFile

    init {
        require(maxBytes > 0) { "Maximum source size must be positive" }
    }

    fun cache(openSource: () -> InputStream?): CachedImageSource {
        if (!directory.exists() && !directory.mkdirs()) {
            throw ImageSourceUnreadableException()
        }
        val target = File.createTempFile(FILE_PREFIX, FILE_SUFFIX, directory)
        check(target.canonicalFile.parentFile == directory)

        try {
            val input = try {
                openSource()
            } catch (error: Exception) {
                throw ImageSourceUnreadableException(error)
            } ?: throw ImageSourceUnreadableException()

            val byteCount = try {
                input.use { source ->
                    FileOutputStream(target).use { output ->
                        copyBounded(source, output).also { output.fd.sync() }
                    }
                }
            } catch (error: ImageSourceTooLargeException) {
                throw error
            } catch (error: Exception) {
                throw ImageSourceUnreadableException(error)
            }
            if (byteCount == 0L) {
                throw ImageSourceUnreadableException()
            }
            return CachedImageSource(target, byteCount)
        } catch (error: Exception) {
            target.delete()
            throw error
        }
    }

    fun delete(file: File?) {
        if (file == null) return
        try {
            val target = file.canonicalFile
            if (target.parentFile == directory && target.isFile) {
                target.delete()
            }
        } catch (_: IOException) {
            // Best-effort cleanup inside the app-private cache only.
        }
    }

    /** Resolves only an opaque filename generated by this cache. */
    fun resolve(token: String?): File? {
        if (
            token.isNullOrBlank() ||
            token != File(token).name ||
            !token.startsWith(FILE_PREFIX) ||
            !token.endsWith(FILE_SUFFIX)
        ) {
            return null
        }
        return try {
            val target = File(directory, token).canonicalFile
            target.takeIf { it.parentFile == directory && it.isFile }
        } catch (_: IOException) {
            null
        }
    }

    fun deleteToken(token: String?) {
        delete(resolve(token))
    }

    /** Deletes only generated files that are not referenced by a loaded archive. */
    fun deleteUnreferencedTokens(retainedTokens: Set<String>) {
        directory.listFiles().orEmpty().forEach { candidate ->
            val token = candidate.name
            if (
                token !in retainedTokens &&
                token.startsWith(FILE_PREFIX) &&
                token.endsWith(FILE_SUFFIX)
            ) {
                delete(candidate)
            }
        }
    }

    private fun copyBounded(input: InputStream, output: FileOutputStream): Long {
        val buffer = ByteArray(COPY_BUFFER_SIZE)
        var total = 0L
        while (true) {
            val count = input.read(buffer)
            if (count < 0) break
            if (count == 0) continue
            if (count.toLong() > maxBytes - total) {
                throw ImageSourceTooLargeException()
            }
            output.write(buffer, 0, count)
            total += count
        }
        return total
    }

    companion object {
        private const val FILE_PREFIX = "source-"
        private const val FILE_SUFFIX = ".img"
        private const val COPY_BUFFER_SIZE = 64 * 1024
    }
}
